[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = [512, 512]
batch_size = 2
enable_bucket= true
max_bucket_reso = 1024
min_bucket_reso = 128
bucket_reso_steps = 64

    [[datasets.subsets]]
    image_dir = './images_tags_final'
    metadata_file = './images_tags_final'
    keep_tokens = 1
    flip_aug = true
    num_repeats = 5
    

